### ISSUE TITLE
send_lldp.py does not work

### ISSUE THREAD

**Issue by zhangineer2** [Martolins/Hierarchical-SDN-using-Kathara#1]
I am getting an error while trying to run `send_lldp.py`. Some research shows that this maybe an issue with lower version of scapy. When I run this script on python 3.8 with scapy 2.4.5 on my host, I did not run into this issue. How, can I upgrade the docker container to python 3.8 ?

root@h1:/# python3 send_lldp.py 
Traceback (most recent call last):
  File "send_lldp.py", line 4, in <module>
    from scapy.contrib import lldp
  File "/usr/lib/python3/dist-packages/scapy/contrib/lldp.py", line 682, in <module>
    class LLDPDUGenericOrganisationSpecific(LLDPDU):
  File "/usr/lib/python3/dist-packages/scapy/contrib/lldp.py", line 702, in LLDPDUGenericOrganisationSpecific
    ByteField('subtype', 0x00),
NameError: name 'ByteField' is not defined

**Comment by zhangineer2** [comment]
i was able to resolve this issue by building a new docker container with python 3.8.12 and installed a newer version of scap
